# Ring 0: ADOPT
# Ring 1: TRIAL
# Ring 2: ASSESS
# Ring 3: HOLD

date: "2025.05"
entries:
  quadrants:
    datastores:
      - ring: 0
        label: "MSSQL"
        active: true
        moved: 0
      - ring: 2
        label: "REDIS"
        link: "https://redis.io/"
        active: true
        moved: 0
      - ring: 2
        label: "Infinispan"
        active: true
        moved: 0
    infrastructure:
      - ring: 0
        label: "Tekton"
        active: true
        moved: 0
      - ring: 2
        label: "Test Containers Cloud"
        active: true
        link: "https://testcontainers.com/cloud/"
        moved: 0
      - ring: 0
        label: "Kubernetes"
        active: true
        moved: 0
      - ring: 0
        label: "Docker"
        active: true
        moved: 0
    datamanagement:
      []
    languages:
      - ring: 0
        label: "Python"
        active: true
        moved: 0
      - ring: 0
        label: "Java"
        active: true
        moved: 0
      - ring: 0
        label: "C#"
        active: true
        moved: 0